- name: create archive and copy to hosts
  hosts: app01, app02, app03
  become: true
  tasks:
    - name: as per data create an archive file and set owner
      archive:
        path: /usr/src/sysops
        dest: /opt/sysops/beta.tar.gz
        format: gz
        force_archive: yes
        owner: "{{ansible_user}}"
        group: "{{ansible_user}}"